# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OCDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'XHLaunchAd', '~> 3.9.8' # 启动页 很完善
pod 'EAIntroView', '~> 2.12.0' # 引导页 很不错
pod 'CYLTabBarController', '~> 1.28.4'
pod 'YTKNetwork', '~> 2.0.4' # 依赖AFNetworking3.0以上
pod 'SDCycleScrollView', '~> 1.80' # 依赖SDWebImage 5.0以上
pod 'IGListKit', '~> 3.4.0'
pod 'QMUIKit', '~> 4.0.3'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh','~> 3.1.12'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'Toast', '~> 3.1.0'
pod 'MBProgressHUD','~> 1.0.0'
pod 'TZImagePickerController', '~> 3.2.7'
#pod 'IDMPhotoBrowser', '~> 1.11.3' #依赖SDWebImage 与SDCycleScrollView冲突,先导入SDCycleScrollView
pod 'SGQRCode', '~> 3.0.1' # 扫码
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'PPNumberButton', '~> 0.8.0'
pod 'MZFormSheetPresentationController', '~> 2.4.3'
pod 'DateTools', '~> 2.0.0'
pod 'BGFMDB', '~> 2.0.9'
pod 'YYModel', '~> 1.0.4'
pod 'YYText', '~> 1.0.7'
pod 'YYCategories', '~> 1.0.4'
pod 'RRSwipeCell', '~> 0.1.1'
pod 'HMSegmentedControl', '~> 1.5.3'
pod 'WMPageController', '~> 2.5.2'
pod 'XLForm', '~> 4.1.0'
pod 'IQKeyboardManager', '~> 6.5.4'

end
